### ISSUE TITLE
Turn of the Andy Matuschak mode for vertical title bar 

### ISSUE THREAD

**Issue by WRoestorf** [chad-bennett/warmth-obsidian-theme#1]
Hi. Is there a setting to turn the Andy Matuschak mode for vertical title bar off, or to revert back to a title bar at the top of the note..?

**Comment by chad-bennett** [comment]
Yes there is. If you scroll to the bottom of the code there is a section for the Andy mode. It starts at line 330 and goes to line 407.

You can either delete the entire section or move the close comment */ at the end of 330 to end of line 407 to comment it out. Moving that */ back and forth allows you to turn the mode on or off. Does that make sense? 

Sometimes wish there was an easy toggle versus editing code, but that's how it works. Let me know if you have any other questions. 

chad

**Comment by WRoestorf** [comment]
Thank you for the answer, much appreciated.
